worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # upstream-сервисы
    # имена совпадают с именами сервисов в docekr-compose.yml (Docekr DNS)

    upstream auth_service {
        server auth-service:8081;
    }

    upstream stt_service {
        server stt-service:8082;
    }

    upstream tts_service {
        server tts-service:8083;
    }

    upstream data_service {
        server data-service:8084;
    }

    # timeout`s, для избежания блокировки Gateway

    proxy_connection_timeout 3s;
    proxy_send_timeout 10s;
    proxy_read_timeout 10s;


    # нужно ли?
    # rate limit по ip
    limit_req_zode $binary_remote_addr zone=api_limit:10m rate=20r/s;

    server {
        listen 80;
        server_name _;

        # 1. Публичные маршруты Auth Service - без auth_request,
        # т.к. на login/register/refresh у юзера ещё нет токена

        location /auth/api {
            limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Внутренний location Для проверки токена.
        # Не вызывается напрямую снаружи (internal) - только через auth_request

        location = /internal/validate {
            internal;
            proxy_pass http://auth_service/validate;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            # Прокидываем заголовок Authorization из начального запроса
            proxy_set_header Authorization $http_authorization;
        }

        # 3. Защищённые маршруты - сначала auth_request, затем проксирование

        location /api/stt/ {
            limit_req_zone=api_limit burst=10 nodelay;
            
            auth_request /internal/validate;
            auth_request_set $user_id $upstream_http_x_user_id;

            proxy_pass http://stt_service/;
            proxy_set_header Host $host;
            proxy_set_header X-User-Id $user_id;
        }

        location /api/tts/ {
            limit_req_zone=api_limit burst=10 nodelay;
            
            auth_request /internal/validate;
            auth_request_set $user_id $upstream_http_x_user_id;

            proxy_pass http://tts_service/;
            proxy_set_header Host $host;
            proxy_set_header X-User-Id $user_id;
        }

        location /api/data/ {
            limit_req_zone=api_limit burst=10 nodelay;

            auth_request /internal/validate;
            auth_request_set $user_id $upstream_http_x_user_id;

            proxy_pass http://data_service/;
            proxy_set_header Host $host;
            proxy_set_header X-User-Id $user_id;
        }

        # Если токена нет/просрочен/невалиден 
        error_page 401 = /401_json;
        location = /401_json {
            internal;
            default_type application/json;
            return 401 '{"error": "Unathorized"}';
        }
    }
}
